### ISSUE TITLE
Enlaces a páginas de Ponentes y Programa están rotos

### ISSUE THREAD

**Issue by leogg** [wpnicaragua/WCMGA2019-Landing-Custom-CSS#72]
Los enlaces a las páginas de ponentes y programa desde Home están rotos>

https://2019.managua.wordcamp.org/ponentes-2/
https://2019.managua.wordcamp.org/programa-2/

**Comment by alexcu21** [comment]
Done

**Comment by alexcu21** [comment]
Done
