### ISSUE TITLE
Logos de sponsors en móvil están distorsionados

### ISSUE THREAD

**Issue by leogg** [wpnicaragua/WCMGA2019-Landing-Custom-CSS#73]
Logos de sponsors en móvil están distorsionados
![Screenshot_2019-03-26-08-06-44](https://user-images.githubusercontent.com/2543067/55004923-06114680-4fd3-11e9-89bb-638b0c9c4932.png)

**Comment by amarquez05** [comment]
En version web, no siguen una estructura jerarquica, esmeralda esta en pequeño, y los demas que son patrocinadores mas pequeños, el logo esta mas chiqui: http://prntscr.com/n39bb4

**Comment by amarquez05** [comment]
update del look en movil, aiuda: http://prntscr.com/n4v88k
