### ISSUE TITLE
Footer en desktop tiene un gran espacio en blanco

### ISSUE THREAD

**Issue by leogg** [wpnicaragua/WCMGA2019-Landing-Custom-CSS#74]
Footer en desktop tiene un gran espacio en blanco. Probado en Mozilla Firefox y Chrome.

![Screenshot from 2019-03-26 14-27-39](https://user-images.githubusercontent.com/2543067/55005212-7fa93480-4fd3-11e9-82de-23cd233dd36d.png)

**Comment by amarquez05** [comment]
Holis, ahora este quedo cortado: http://prntscr.com/n39bnr
Y en mobile todavia se ve en blanco una parte

Sorry la joda

**Comment by amarquez05** [comment]
#update - en web se mira culito, pero mobile sigue malo http://prntscr.com/n4v7p9
