### ISSUE TITLE
Speakers profile

### ISSUE THREAD

**Issue by amarquez05** [wpnicaragua/WCMGA2019-Landing-Custom-CSS#79]
Hola,
Pasaba a pedirles un par de cosa aqui:

- Reducir el tamaño de las fotos http://prntscr.com/n397g5
- Y si estas de la pagina principal (https://2019.managua.wordcamp.org/speakers/) y clickeas sobre el nombre/foto de un speaker, no se abre su perfil

**Comment by burzumumbra** [comment]
La única solución que tenemos es agregar esta opción al shortcode. Pero solo aplicara a el nombre, la foto no es linkeable.

> speaker_link
Where the speakers name should link to, if anything. Available values: “permalink” for the speaker’s individual post, or leave blank to not link anywhere. Defaults to not linking anywhere.

**Comment by burzumumbra** [comment]
@amarquez05 Arreglado en este commit.
[Speaker Single photo - name link](https://github.com/wpnicaragua/WCMGA2019-Landing-Custom-CSS/commit/884b157ef6fc8c0d95ebe1110b955f6ebca0b589)

Espero confirmación si eso arregla este issue.

**Comment by alexcu21** [comment]
puedo cerrar este issue?

**Comment by burzumumbra** [comment]
> puedo cerrar este issue?

Ya le dejo como cerrado.
