### ISSUE TITLE
FOLD | Se acabo la espera

### ISSUE THREAD

**Issue by amarquez05** [wpnicaragua/WCMGA2019-Landing-Custom-CSS#80]
Hola, en el segundo fold, donde va el texto de "se acabo la espera..." 
despues de los iconos tanto en mobile como desktop se ve un gran espacio blanco

http://prntscr.com/n398uo

Se podria ajustar pls?

**Comment by alexgordon25** [comment]
Procediendo...

**Comment by alexgordon25** [comment]
![image](https://user-images.githubusercontent.com/2489382/55267783-1d0d9e00-524a-11e9-934b-3235c1cfcf4a.png)
