### ISSUE TITLE
Logo blanco

### ISSUE THREAD

**Issue by amarquez05** [wpnicaragua/WCMGA2019-Landing-Custom-CSS#81]
El logo se ve altamente pixeleado
http://prntscr.com/n399mw

Se puede cambiar pls?

**Comment by alexcu21** [comment]
exportalo en 1200 x 1200 px y enviamelo

**Comment by alexgordon25** [comment]
Procediendo con este cambio...

**Comment by alexgordon25** [comment]
![image](https://user-images.githubusercontent.com/2489382/55264990-f7799800-523b-11e9-8520-0f7a4ed96ac9.png)
